// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcznpqmeofvktvwklggb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjem5wcW1lb2Z2a3R2d2tsZ2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzU1OTEsImV4cCI6MjA3NDAxMTU5MX0.kBvFf2iFtTWiSCtpFoEdKp4vXCVir70PBeHibXxJY5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});